name: Build Release

on: 
  release:
    types: [created]

jobs:
  release-matrix:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, 386]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'
    - name: Install Dependencies
      run: go mod tidy
    - name: Build and Release
      uses: wangyoucao577/go-release-action@v1.16
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "jcli"
